### ISSUE TITLE
Fehler beim Upload von LRMI Metadaten

### ISSUE THREAD

**Issue by nil-mm** [hbz/to.science.api#348]
Beim Upload von LRMI-Metadaten über den Endpunkt `/resource/{pid}/lrmiData` wird ein Fehler gemeldet.

Das entsprechende JSON ist ein offizielles Beispiel: [Example mainEntityOf.json](https://github.com/dini-ag-kim/lrmi-profile/blob/main/draft/examples/valid/mainEntityOf.json)

Hier sind die durchgeführten Befehle

```
# Create Resource
curl --key key.pem --cert cert.pem \
    -X PUT \
    -u $USER:$PW \
    -H "Accept: application/json" \
    -H'content-type:application/json' \
    -d'{"contentType":"monograph","accessScheme":"public"}' \  
    $APIURL/resource/lrmitest:cb547fe3-16df-4b05-a6af-229d66dad2d9 

# result
# {"text":"lrmitest:cb547fe3-16df-4b05-a6af-229d66dad2d9 created/updated!","code":200}

# Metadata Upload
curl --key key.pem --cert cert.pem \
    -X POST \
    -u $USER:$PW \
    -H "Accept: application/json"  \
    --data-binary @lrmi.json -H'content-type:application/json' \ 
    $APIURL/resource/lrmitest:cb547fe3-16df-4b05-a6af-229d66dad2d9/lrmiData 

# Resul
# {"error":"....","code":500}
```
Die Stacktrace lautet:

```
helper.HttpArchiveException: actions.Modify$UpdateNodeException: helper.HttpArchiveException: archive.fedora.RdfException: org.eclipse.rdf4j.rio.RDFParseException: IRI includes string escapes: '\34' [line 16]
	at controllers.Resource.lambda$updateLrmiData$18(Resource.java:489)
	at controllers.MyController$ModifyAction.lambda$call$0(MyController.java:525)
	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: actions.Modify$UpdateNodeException: helper.HttpArchiveException: archive.fedora.RdfException: org.eclipse.rdf4j.rio.RDFParseException: IRI includes string escapes: '\34' [line 16]
	at actions.Modify.updateLobidify2AndEnrichLrmiData(Modify.java:209)
	at controllers.Resource.lambda$updateLrmiData$18(Resource.java:483)
	... 11 more
Caused by: helper.HttpArchiveException: archive.fedora.RdfException: org.eclipse.rdf4j.rio.RDFParseException: IRI includes string escapes: '\34' [line 16]
	at actions.Modify.updateMetadata2(Modify.java:1158)
	at actions.Modify.updateLobidify2AndEnrichLrmiData(Modify.java:325)
	at actions.Modify.updateLobidify2AndEnrichLrmiData(Modify.java:207)
	... 12 more
Caused by: archive.fedora.RdfException: org.eclipse.rdf4j.rio.RDFParseException: IRI includes string escapes: '\34' [line 16]
	at archive.fedora.RdfUtils.readRdfToGraph(RdfUtils.java:235)
	at actions.Modify.rewriteContent(Modify.java:446)
	at actions.Modify.updateMetadata2(Modify.java:1147)
	... 14 more
Caused by: org.eclipse.rdf4j.rio.RDFParseException: IRI includes string escapes: '\34' [line 16]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:322)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:596)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.reportError(NTriplesParser.java:635)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseUriRef(NTriplesParser.java:436)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseObject(NTriplesParser.java:385)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:289)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:176)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:116)
	at archive.fedora.RdfUtils.readRdfToGraph(RdfUtils.java:232)
	... 16 more
","text":"actions.Modify$UpdateNodeException: helper.HttpArchiveException: archive.fedora.RdfException: org.eclipse.rdf4j.rio.RDFParseException: IRI includes string escapes: '\34' [line 16]
```

**Comment by inkuss** [comment]
Hallo @nil-mm ,
das war ein Problem mit dem Datenmodell. Ich hatte von irgendwo (weiß nicht mehr woher) her die Information, dass LRMI license ein Skalar (String) ist. Lt. DINI-Spezifikation ist es aber ein Object.
Ich habe das Mapping geändert, auf hoerkaen neu ausgerollt und jetzt geht`s.

Z.B. 
curl -i $USR:$PASSWD --key metromorph.key --cert metromorph.crt -XPOST https://api.hoerkaen.hbz-nrw.de/resource/oer:17/lrmiData --data-binary '@mainEntityOf.json'  -H "Content-Type:application/json;charset=utf-8";echo
{"text":"oer:17 LRMI-metadata of oer:17 successfully updated! \noer:17 LRMI-metadata successfully updated, lobidified and enriched! Enrichment of oer:17 succeeded!","code":200}

**Comment by nil-mm** [comment]
Super. Funktioniert. Auch mit Beispielen aus den angepassten ORCA Schemas.
